create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  title text not null,
  amount numeric(12, 2) not null check (amount > 0),
  category text not null default 'Khac',
  transaction_date date not null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists transactions_transaction_date_idx
  on public.transactions (transaction_date desc, created_at desc);

alter table public.transactions enable row level security;

drop policy if exists "Allow public read transactions" on public.transactions;

create policy "Allow public read transactions"
  on public.transactions
  for select
  using (true);

drop policy if exists "Allow public insert transactions" on public.transactions;

create policy "Allow public insert transactions"
  on public.transactions
  for insert
  with check (true);

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  description text not null,
  category text not null default 'general',
  metadata jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists tasks_created_at_idx
  on public.tasks (created_at desc);

alter table public.tasks enable row level security;

drop policy if exists "Allow public read tasks" on public.tasks;

create policy "Allow public read tasks"
  on public.tasks
  for select
  using (true);

drop policy if exists "Allow public insert tasks" on public.tasks;

create policy "Allow public insert tasks"
  on public.tasks
  for insert
  with check (true);